version: "3"
services:
  client: 
    build: ./client
    container_name: client_c
    ports:
      - '3000:3000'
    volumes:
      - ./client:/c
      - /c/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - server
    networks:
      - mern-network

  server: 
    build: ./server
    container_name: server_c
    restart: always
    ports:
      - '5000:5000'
    volumes:
      - ./server:/s
      - /s/node_modules
    networks:
      - mern-network


networks:
  mern-network:
    driver: bridge
